controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

catch_all:
    path: /{catchall}
    controller: App\Controller\HomeController::index
    requirements:
        catchall: ".*"

